name: localservice
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.9+16

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  flutter_sticky_header: ^0.6.4
  flutter_rating_bar: ^4.0.1
  percent_indicator: ^4.2.2
  json_annotation:
  dio: ^5.1.1 
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  accordion: ^2.5.1
  dotted_border: ^2.0.0+2
  flutter_chat_ui: ^1.6.6
  carousel_slider: ^4.1.1
  flutter_html: ^3.0.0-alpha.5
  favorite_button: ^0.0.4
  image_picker: ^0.8.5+3
  extended_image: ^7.0.0
  file_picker: ^5.2.0+1
  mime: ^1.0.2
  uuid: ^3.0.6
  photo_view: ^0.14.0
  country_icons: ^2.0.2
  socket_io_client: ^2.0.0
  loading_indicator: ^3.1.0
  rxdart: ^0.27.5
  share_plus: ^6.3.1
  go_router: ^6.0.2
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.6
  webview_flutter: ^4.0.2
  geolocator: ^9.0.2
  dropdown_search: ^5.0.3
  flutter_staggered_grid_view: ^0.6.2
  video_player: ^2.4.7
  chewie: ^1.3.5
  path_provider: ^2.0.11
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.2.0
  top_snackbar_flutter: ^3.0.0
  flutter_advanced_avatar: ^1.1.0
  buttons_tabbar: ^1.3.6
  flutter_wizard: ^2.0.5
  step_progress_indicator: ^1.0.2
  flutter_verification_code: ^1.1.6
  skeletons: ^0.0.3
  location: ^4.4.0
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  overlay_support: ^2.1.0
  flutter_local_notifications: ^13.0.0
  upgrader: ^6.2.0
  flutter_phone_direct_caller: ^2.1.1
  device_info_plus: ^8.0.0
  platform_device_id: ^1.0.1
  web_socket_channel: ^2.3.0
  uni_links: ^0.5.1
  just_audio_windows: ^0.2.0
  just_audio: ^0.9.31
  flutter_sound: ^9.2.13
  msix: ^3.7.0
  in_app_purchase: ^3.1.5
  pay: ^1.1.0   
  flutter_stripe: ^9.0.0+1
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  quick_actions: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  ios: true
  android: true
  image_path: "assets/localservice_launcher_icon.png"
  apaptive_icon_background: "#191919"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/
msix_config:
  display_name: Recomand
  publisher_display_name: Jobdone SRL
  identity_name: JobdoneSRL.Recomand
  logo_path: 'D:\BEAR\WORK\Krakiun\localservice\windows\runner\resources\app_icon.ico'
  store: true
  publisher: CN=3B37F289-74D7-46D7-A438-173E1F26661F
  capabilites: runFullTrust
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    # - family: Muli
    #   fonts:
    #     - asset: assets/fonts/muli/Muli.ttf
    #     - asset: assets/fonts/muli/Muli-Bold.ttf
    #       weight: 700
    #     - asset: assets/fonts/muli/Muli-Light.ttf
    #       weight: 300
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
    - family: Original Surfer
      fonts:
        - asset: assets/fonts/Original_Surfer/OriginalSurfer-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
